development: 
  adapter: postgresql
  encoding: unicode
  database: prebelt_development
  pool: 5
  username: ubuntu
  password: 

test: 
  adapter: postgresql
  encoding: unicode
  database: prebelt_test
  pool: 5
  username: ubuntu
  password: 

production: 
  adapter: postgresql
  encoding: unicode
  database: prebelt_production
  pool: 5
  username: ubuntu
  password: